name: Build, Push Docker Image, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/airline-order-course:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/airline-order-course:${{ github.sha }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            mkdir -p ~/airline-cicd
            cd ~/airline-cicd

            # 1) 把仓库里的 docker-compose.yml 写到 EC2
            cat > docker-compose.yml <<'EOF'
            version: "3.9"
            services:
              app:
                image: ${{ secrets.DOCKERHUB_USERNAME }}/airline-order-course:latest
                container_name: airline-app
                ports:
                  - "80:8080"
                environment:
                  - SERVER_ADDRESS=0.0.0.0
                depends_on:
                  - db
              db:
                image: mysql:8.0
                container_name: airline-mysql-db
                environment:
                  MYSQL_ROOT_PASSWORD: airlineTest1234
                  MYSQL_DATABASE: airline_order_db
                ports:
                  - "3306:3306"
            EOF

            # 2) 启动
            docker-compose pull
            docker-compose up -d --remove-orphans
            docker-compose ps
